# Generated by Django 3.2.25 on 2024-10-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0005_history_dateindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfbotBranch',
            fields=[
                ('patch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cfbot_branch', serialize=False, to='commitfest.patch')),
                ('branch_id', models.IntegerField()),
                ('branch_name', models.TextField()),
                ('commit_id', models.TextField(blank=True, null=True)),
                ('apply_url', models.TextField()),
                ('status', models.TextField(choices=[('testing', 'Testing'), ('finished', 'Finished'), ('failed', 'Failed'), ('timeout', 'Timeout')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CfbotTask',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('task_name', models.TextField()),
                ('branch_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('status', models.TextField(choices=[('CREATED', 'Created'), ('NEEDS_APPROVAL', 'Needs Approval'), ('TRIGGERED', 'Triggered'), ('EXECUTING', 'Executing'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted'), ('ERRORED', 'Errored')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfbot_tasks', to='commitfest.patch')),
            ],
        ),
    ]
