# Generated by Django 3.2.25 on 2024-12-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0006_cfbot_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbottask',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Created'), ('NEEDS_APPROVAL', 'Needs Approval'), ('TRIGGERED', 'Triggered'), ('EXECUTING', 'Executing'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('SCHEDULED', 'Scheduled'), ('ABORTED', 'Aborted'), ('ERRORED', 'Errored')]),
        ),
    ]
